### ISSUE TITLE
Redirect to TrebleShot browser share page in receiver device

### ISSUE THREAD

**Issue by subins2000** [genonbeta/TrebleShot#107]
**Is your feature request related to a problem? Please describe.**
Having to manually type the browser share URL in the receiving device

**Describe the solution you'd like**
Y'know when you login to a WiFi that has a login page so that the phone automatically redirects to that login page ? How about we implement that in TrebleShot. As the user connects to the sender's hotspot, the login is required message from android shows up and redirects to the TrebleShot page where the files are shown.

**Describe alternatives you've considered**
This is a good alternative to the existing manually type.

**Additional context**
![](https://www.download3k.com/article_images/0/1852/full_1_a6565e6ce173bc09d50103a7d4b10fb5.png)

**Comment by velitasali** [comment]
Hey! I don't know if any API is present to make this happen, so, I will update this accordingly. Also, if you know any example, feel free to share.

**Comment by mubashir-rehman** [comment]
I have searched it on Google. The request is to provide a "Captive Portal" and web server hosted at sender device (I believe), so that on connection a login page or download page appear on receiver device. It seems impossible without Root access. However, even with root it is very difficult. It is required to change the iptables rules.
Following are the links that might help:
https://forum.xda-developers.com/showthread.php?t=2113718&page=2
https://github.com/joschi70/AndroidPirateBox (using PAW)
https://github.com/zahichemaly/fake-captive-portal-using-android-phone
This is what seems to be available by Android (https://developer.android.com/reference/android/net/CaptivePortal)

**Comment by velitasali** [comment]
@mubashir-rehman I see. Thanks for investigating.

The suggestion is actually great, but I don't think the Android framework would allow it in the near future given it would be of no use other than exploiting it for other reasons. So, I am going to close this issue for now.
