### ISSUE TITLE
Feature request: share directories

### ISSUE THREAD

**Issue by DMSalesman** [genonbeta/TrebleShot#13]
Good day.

I recently started to use this app, and I noticed that the possibility to send whole folders seem to be missing. Upon trying to send a folder, the sender says `You are not allowed`, and the list of files to be sent appears as empty. Could you troubleshoot this?

**Comment by velitasali** [comment]
Hi, I'm currently working on that. I want it to work well so it needs a structure that can handle thousands of files. The problem is that both devices have to keep the information of the files in order to be able to continue sending files when a problem occurs. It's not that hard yet my newly bought laptop is broken so I won't be able to work on the project (again) for 15 days. And you're not allowed is not an issue. See this: https://github.com/genonbeta/TrebleShot/issues/1

**Comment by DMSalesman** [comment]
I do know that the access denied is typically not an issue.

In this case I believe it is, though, since I sent a bunch of files immediately before and just after trying to send a whole directory, and the TrebleShot sender complained only when sending the directory, while each individual file was transferred flawlessly.

Anyway, it's nice to know that the work is progressing smoothly. Fair fortune to you, as this piece of software really has potential.

**Comment by velitasali** [comment]
I had to temporarily remove the folder sending feature with 1.2.2 since it wasn't working as it's supposed to. I'm sure it says (empty) when you only choose folders to send which means no file is available to send. I'm hoping to complete it with the next mojor release 1.2.3 which will hopefully be able to create nested folder structure. And thanks for your nice comment I'm sure I can create an app needed with your support :)

**Comment by DMSalesman** [comment]
Excellent. I'll close the issue after the folder sending feature is implemented and deemed stable.

**Comment by velitasali** [comment]
The feature has been successfully implemented and is present in the latest release. You should give it a try and let me know what you think. Thanks.

**Comment by DMSalesman** [comment]
Good to know. Once the latest release becomes available via F-Droid, I'll test the feature and report my findings.

**Comment by velitasali** [comment]
I should point out that F-Droid is currently compiling 1.2.3 which isn't the latest release. However, you can still send folders by choosing them but without nested structure.

**Comment by DMSalesman** [comment]
Got it. I will wait for F-Droid to serve the latest release with nested directories, and will give my feedback then.

In the meantime, I'll close this issue. I'll reopen it if some problem arises.
