### ISSUE TITLE
Stuck at 'Obtaining IP address'

### ISSUE THREAD

**Issue by anudeepND** [genonbeta/TrebleShot#49]
I was not able to connect to a TrebleShot, it's stuck at Obtaining IP address, what am I doing wrong?
#### Edit:
All permissions are given to the app. Device is running on Android 7.1.2

![screenshot_20180409-163857](https://user-images.githubusercontent.com/26179946/38494867-1ffa9ec0-3c15-11e8-8b15-49f52b3a1c07.png)

**Comment by velitasali** [comment]
Looks like it is a device specific issue. There is a little can be done on the application side. But the helpful suggestions would be if the problem still persists;

1- Renaming the network name to all lower case omitting special characters like "_", "-" while the network security type is kept "open (not password protected)".
2- Setting up a hotspot that is password protected.
3- Restarting both of the devices.
4- Checking the device allowance is set to all rather than to specific or known devices. This feature as far as I know present on some OEM devices like Samsung and ASUS. You might want to double check this because this one is likely to be the cause.
4- Trying to lower the frequency of the broadcast from 5ghz to 2.4ghz.

If the one is your case please let me know. Good luck.

**Comment by anudeepND** [comment]
Thanks for the info @velitasali, I was able solve this issue by removing underscore from the WiFi network name. Also it was already in the 2.4GHz band.
