### ISSUE TITLE
LocalOnlyHotspotCallback

### ISSUE THREAD

**Issue by MyGiHubSpace** [genonbeta/TrebleShot#52]
After i clone and build , i get this message
Failed to find byte code for android/net/wifi/WifiManager$LocalOnlyHotspotCallback

Help me

**Comment by velitasali** [comment]
This is a known issue for Android Studio 3.1.{?} and it is already reported on issue tracker and this only applies to you if you are running Android Studio 3.1 of course. 

To fix it temporarily you should disable Instant Run in the settings if the problem persists and since trebleshot always runs a second process, this won't change compile times anyway. 

![screenshot from 2018-05-29 10-33-49](https://user-images.githubusercontent.com/10258162/40644607-5fdc7f8e-632c-11e8-8521-ee3e8679883d.png)

**Comment by MyGiHubSpace** [comment]
Thanks. It s work now
