### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by BoFFire** [genonbeta/TrebleShot#64]
Hi,
I noticed an issue with the display of QR Code when I click on Create Wi-Fi AP, the QR Code doesn't appear. But when switching themes it reappeared.

Système : Android 6
Theme : Dark
Version : The latest βeta

**Comment by velitasali** [comment]
@BoFFire Thank you. I was trying to figure out why it is happening and still did not find it but probably because I was hiding one bitmap while trying make another appear and it seems that it causes miscalculation, strange issues.  probably will be gone with the next release.

https://github.com/genonbeta/TrebleShot/blob/c1cff486b5bde3e0cda0e56f276753893c5f49db/app/src/main/java/com/genonbeta/TrebleShot/fragment/NetworkStatusFragment.java#L250
