### ISSUE TITLE
What type of data third party libraries get ?

### ISSUE THREAD

**Issue by FaizKhan5** [genonbeta/TrebleShot#73]
"With these third-party libraries contained in the software, your information, including personal data, may be transferred to computers located outside of your state"

I read privacy policy but it's not clear that what type of personal data and info transferred. Is it a personal media files or some meta data or what ?

**Comment by velitasali** [comment]
> "With these third-party libraries contained in the software, your information, including personal data, may be transferred to computers located outside of your state"
> 
> I read privacy policy but it's not clear that what type of personal data and info transferred. Is it a personal media files or some meta data or what ?

Not exactly. Please first refer to the merge request made this change: https://github.com/genonbeta/TrebleShot/pull/63#discussion_r223305965 

I suggest you read all comments on the changes. Especially this one: https://github.com/genonbeta/TrebleShot/pull/63/commits/b1e477a7d184065826fb737b61183a847655d638

**Comment by FaizKhan5** [comment]
I read all but what personal data libraries get? It's not clear that what type of personal data ?

**Comment by velitasali** [comment]
@FaizKhan5 Currently there are only a few libraries that made into actual compiled code. Most the third party libraries shown in the app are just helping compilation itself and currently there is no library that helps collect or should be collecting data. The only real internet connection happens when you enter about section where it shows contributors, change log and etc. The information is gathered from GitHub with no information revealing your identity. If you use Google Play version there should be donation implementation using Google In App Purchases service. If you donate, your Google account will be associated with the purchase, but I or any developer 
(other than me) using In App Purchases will not be able to see your account information, but the country the purchase was made.

**Comment by FaizKhan5** [comment]
Thank you very much for explaining me in detail.
