### ISSUE TITLE
NEW: You can start sending files (previously only receiver could start the transfer) ?

### ISSUE THREAD

**Issue by realrufans** [genonbeta/TrebleShot#84]
Good day PO,
Good to see the new update. But, I don't think if I got your point in this part of the update. 
**NEW: You can start sending files (previously only receiver could start the transfer)**

Because, in v1.3.0, I can successfully initiate a transfer by clicking **Send**, picking the app, clicking on the + sign, and setting up a hotspot.

**Comment by velitasali** [comment]
Hi @realrufans, it used to be that when you wanted to start the transfer process, you needed to tap one of confirmation buttons on receiver device like;
* When you are viewing an individual transfer process, you could click the 'Receive' button.
* When you see the notification for transfer request, you could again click the 'Receive' button on the notification.

New version adds a 'Send' button to sender side. This allows sender to start transfer when the following requirements are met;
* The sender is a TrustZone device on the receiver side. This is required because otherwise anyone could start sending, which is dangerous.

**Comment by realrufans** [comment]
Okay, I will text Downgrade TrebleShot on my devices to confirm this.

**Comment by realrufans** [comment]
Hello,  I have tried this feature on v1.4 and  v1.3 but I see no difference. 
Maybe someone else should try this.
Or maybe a screenshot will help ?

#### Issues

I didn't get **Send button** on senders side. ( As notification ). But, I got 'receive' button on receiving device. Same situation on  [ V1.3 & 1.4).
**Sender is  on TrustZone.**

**Comment by realrufans** [comment]
I just got it .😊

Nice job 👍
